[FEATURE] Criei a pagina de onboarding
Lifeados/authentication-app pull request #5
Opened 2024-09-16 00:04 UTC by alineamorimdev

Essa PR tem como objetivo criar a pagina de onboarding que direciona para a pagina de splash em 5 segundos.

![Splash](https://github.com/user-attachments/assets/0611a9df-82a0-43f2-a031-4756d306b489)

2024-09-17 23:29 UTC, gabriellsonn requested changes

2024-09-17 23:29 UTC, gabriellsonn commented on lib/ui/modules/onboard/onboard_page.dart
> +      //   Navigator.of(context).pushReplacementNamed('/splash');
@alineamorimdev remova este código, pois ainda não será utilizado.

2024-09-17 23:29 UTC, gabriellsonn commented on lib/ui/modules/onboard/onboard_page.dart
> +    return MaterialApp(
@alineamorimdev o MaterialApp ja existe no arquivo main.dart, por gentileza remova-o.

2024-09-19 23:04 UTC, Lifeados approved these changes

2024-09-19 23:04 UTC, merged