[FEATURE] Adicionando a tela Register
Lifeados/authentication-app pull request #6
Opened 2024-09-17 02:24 UTC by LucasSakuma

Essa PR tem objetivo de adicionar a parte visual da tela register e adicionar a rota da mesma na main.dart

2024-09-17 02:32 UTC, LucasSakuma commented
![image](https://github.com/user-attachments/assets/243921aa-921f-4b3e-b901-49a617501be7)

2024-09-18 23:15 UTC, dionedev commented on lib/ui/modules/register/register_page.dart
> +                    hintText: 'Type your name',
Por gentileza, adicione uma cor para o texto de placeholder conforme o figma (rgba(158, 158, 158, 1))

propriedade: hintStyle

2024-09-18 23:17 UTC, dionedev commented on lib/ui/modules/register/register_page.dart
> +                  hintText: 'Type your email',
O mesmo do comentario anterior

2024-09-18 23:17 UTC, dionedev commented on lib/ui/modules/register/register_page.dart
> +                    hintText: 'Type your password',
O mesmo do comentario anterior

2024-09-18 23:22 UTC, dionedev requested changes
Ao testar no emulador iphone 13 mini, esta ocorrendo overflow na tela sem o teclado e quando o teclado aparece.

<br>

![Simulator Screenshot - iPhone 13 mini - 2024-09-18 at 20 05 51](https://github.com/user-attachments/assets/9f450325-5d72-459e-ba65-60345af8a928)
![Simulator Screenshot - iPhone 13 mini - 2024-09-18 at 20 06 00](https://github.com/user-attachments/assets/0b4da772-9f52-4d4a-ae5d-2cf7dae70350)

2024-09-19 00:42 UTC, LucasSakuma commented
> Ao testar no emulador iphone 13 mini, esta ocorrendo overflow na tela sem o teclado e quando o teclado aparece.
> 
> 
> ![Simulator Screenshot - iPhone 13 mini - 2024-09-18 at 20 05 51](https://private-user-images.githubusercontent.com/115190082/368770990-9f450325-5d72-459e-ba65-60345af8a928.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MDY3NjMsIm5iZiI6MTcyNjcwNjQ2MywicGF0aCI6Ii8xMTUxOTAwODIvMzY4NzcwOTkwLTlmNDUwMzI1LTVkNzItNDU5ZS1iYTY1LTYwMzQ1YWY4YTkyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQwMDQxMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjRmNTgwNjBhNmM1Nzg0ZjRiMmViYmRhZDk4YWUzYWQ0MzllODM0ZjYxZWU2NmJlYzcyYzYwZTA0OWJmMjI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lrQ1IrfZBdQthF-rGpmBzPgv7P6ZYHNTfG0aFjwT0EU) ![Simulator Screenshot - iPhone 13 mini - 2024-09-18 at 20 06 00](https://private-user-images.githubusercontent.com/115190082/368770995-0b4da772-9f52-4d4a-ae5d-2cf7dae70350.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MDY3NjMsIm5iZiI6MTcyNjcwNjQ2MywicGF0aCI6Ii8xMTUxOTAwODIvMzY4NzcwOTk1LTBiNGRhNzcyLTlmNTItNGQ0YS1hZTVkLTJjZjdkYWU3MDM1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQwMDQxMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjU2MDE0Mjc5NzQyODljMjFiNGJhNGFiOGMxNDY0MzA5Mjg2ZTBmNzBjMDJjMWQxZTg5YzJiOTA0MzIyMWY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y1PGP6r9iWbG6uMJ7rfzw87db4qE1k9TwQv4P42k3nc)



> Ao testar no emulador iphone 13 mini, esta ocorrendo overflow na tela sem o teclado e quando o teclado aparece.
> 
> 
> ![Simulator Screenshot - iPhone 13 mini - 2024-09-18 at 20 05 51](https://private-user-images.githubusercontent.com/115190082/368770990-9f450325-5d72-459e-ba65-60345af8a928.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MDY3NjMsIm5iZiI6MTcyNjcwNjQ2MywicGF0aCI6Ii8xMTUxOTAwODIvMzY4NzcwOTkwLTlmNDUwMzI1LTVkNzItNDU5ZS1iYTY1LTYwMzQ1YWY4YTkyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQwMDQxMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjRmNTgwNjBhNmM1Nzg0ZjRiMmViYmRhZDk4YWUzYWQ0MzllODM0ZjYxZWU2NmJlYzcyYzYwZTA0OWJmMjI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lrQ1IrfZBdQthF-rGpmBzPgv7P6ZYHNTfG0aFjwT0EU) ![Simulator Screenshot - iPhone 13 mini - 2024-09-18 at 20 06 00](https://private-user-images.githubusercontent.com/115190082/368770995-0b4da772-9f52-4d4a-ae5d-2cf7dae70350.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MDY3NjMsIm5iZiI6MTcyNjcwNjQ2MywicGF0aCI6Ii8xMTUxOTAwODIvMzY4NzcwOTk1LTBiNGRhNzcyLTlmNTItNGQ0YS1hZTVkLTJjZjdkYWU3MDM1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQwMDQxMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjU2MDE0Mjc5NzQyODljMjFiNGJhNGFiOGMxNDY0MzA5Mjg2ZTBmNzBjMDJjMWQxZTg5YzJiOTA0MzIyMWY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y1PGP6r9iWbG6uMJ7rfzw87db4qE1k9TwQv4P42k3nc)

Ontem ja fiz um commit resolvendo esse erro. o commit era o refactor: resolve auto layout.

2024-09-19 00:42 UTC, LucasSakuma commented on lib/ui/modules/register/register_page.dart
> +                  hintText: 'Type your email',
Corrigido.

2024-09-19 00:42 UTC, LucasSakuma commented on lib/ui/modules/register/register_page.dart
> +                    hintText: 'Type your password',
Corrigido

2024-09-19 01:36 UTC, dionedev approved these changes
Tudo certo...valeu!

2024-09-19 01:38 UTC, merged